[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deepcode-reviewer"
version = "0.1.0"
dependencies = [
    "Flask",
    "google-generativeai",
    "python-dotenv",
]
